# Generated by Django 2.0.4 on 2018-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
